const SALARY_CONFIG = {
  DEFAULT_DAILY_SALARY: 500,
  ALLOWED_LEAVE_DAYS: 5,
  ABSENCE_DEDUCTION_PER_DAY: 100,
  EXTRA_LEAVE_DEDUCTION_PER_DAY: 100
};

const ATTENDANCE_STATUS = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  LEAVE: 'LEAVE',
  HOLIDAY: 'HOLIDAY',
  WEEKEND: 'WEEKEND'
};

const LEAVE_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED'
};

const LEAVE_TYPE = {
  CASUAL: 'Casual Leave',
  MEDICAL: 'Medical Leave',
  ANNUAL: 'Annual Leave',
  EMERGENCY: 'Emergency Leave',
  DUTY: 'Duty Leave',
  // Backward compatibility keys & string values
  'Casual Leave': 'Casual Leave',
  'Medical Leave': 'Medical Leave',
  'Annual Leave': 'Annual Leave',
  'Emergency Leave': 'Emergency Leave',
  'Duty Leave': 'Duty Leave',
  SICK: 'Medical Leave',
  PERSONAL: 'Casual Leave',
  OTHER: 'Duty Leave'
};

const SALARY_STATUS = {
  DRAFT: 'DRAFT',
  CALCULATED: 'CALCULATED',
  APPROVED: 'APPROVED',
  PAID: 'PAID',
  LOCKED: 'LOCKED',
  // Backward compat alias
  PROCESSED: 'CALCULATED'
};

const PAYROLL_STATUS = {
  OPEN: 'OPEN',
  PROCESSING: 'PROCESSING',
  CALCULATED: 'CALCULATED',
  APPROVED: 'APPROVED',
  LOCKED: 'LOCKED'
};

const TEACHER_STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE'
};

const HOLIDAY_TYPE = {
  NATIONAL: 'NATIONAL',
  CUSTOM: 'CUSTOM',
  SCHOOL: 'SCHOOL'
};

const NOTIFICATION_TYPE = {
  LEAVE_SUBMITTED: 'LEAVE_SUBMITTED',
  LEAVE_APPROVED: 'LEAVE_APPROVED',
  LEAVE_REJECTED: 'LEAVE_REJECTED',
  LEAVE_CANCELLED: 'LEAVE_CANCELLED',
  ATTENDANCE_CORRECTED: 'ATTENDANCE_CORRECTED',
  SALARY_CALCULATED: 'SALARY_CALCULATED',
  SALARY_APPROVED: 'SALARY_APPROVED',
  SALARY_PAID: 'SALARY_PAID',
  PAYROLL_OPENED: 'PAYROLL_OPENED',
  PAYROLL_LOCKED: 'PAYROLL_LOCKED',
  TEACHER_CREATED: 'TEACHER_CREATED',
  GENERAL: 'GENERAL'
};

const AUDIT_ACTION = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  TEACHER_CREATED: 'TEACHER_CREATED',
  TEACHER_UPDATED: 'TEACHER_UPDATED',
  TEACHER_DEACTIVATED: 'TEACHER_DEACTIVATED',
  TEACHER_ACTIVATED: 'TEACHER_ACTIVATED',
  ATTENDANCE_MARKED: 'ATTENDANCE_MARKED',
  ATTENDANCE_BULK: 'ATTENDANCE_BULK',
  ATTENDANCE_CORRECTED: 'ATTENDANCE_CORRECTED',
  ATTENDANCE_LOCKED: 'ATTENDANCE_LOCKED',
  LEAVE_APPLIED: 'LEAVE_APPLIED',
  LEAVE_APPROVED: 'LEAVE_APPROVED',
  LEAVE_REJECTED: 'LEAVE_REJECTED',
  LEAVE_CANCELLED: 'LEAVE_CANCELLED',
  SALARY_CALCULATED: 'SALARY_CALCULATED',
  SALARY_APPROVED: 'SALARY_APPROVED',
  SALARY_PAID: 'SALARY_PAID',
  PAYROLL_OPENED: 'PAYROLL_OPENED',
  PAYROLL_CALCULATED: 'PAYROLL_CALCULATED',
  PAYROLL_APPROVED: 'PAYROLL_APPROVED',
  PAYROLL_LOCKED: 'PAYROLL_LOCKED',
  HOLIDAY_CREATED: 'HOLIDAY_CREATED',
  HOLIDAY_UPDATED: 'HOLIDAY_UPDATED',
  HOLIDAY_DELETED: 'HOLIDAY_DELETED',
  CONFIG_UPDATED: 'CONFIG_UPDATED'
};

const AUDIT_MODULE = {
  AUTH: 'AUTH',
  TEACHER: 'TEACHER',
  ATTENDANCE: 'ATTENDANCE',
  LEAVE: 'LEAVE',
  SALARY: 'SALARY',
  PAYROLL: 'PAYROLL',
  HOLIDAY: 'HOLIDAY',
  CONFIG: 'CONFIG',
  NOTIFICATION: 'NOTIFICATION'
};

module.exports = {
  SALARY_CONFIG,
  ATTENDANCE_STATUS,
  LEAVE_STATUS,
  LEAVE_TYPE,
  SALARY_STATUS,
  PAYROLL_STATUS,
  TEACHER_STATUS,
  HOLIDAY_TYPE,
  NOTIFICATION_TYPE,
  AUDIT_ACTION,
  AUDIT_MODULE
};
